### PR TITLE
Added optional beautify and xslt flags

### PR DESCRIPTION
**Pull request by shaildyp**

### CODE REVIEW

**Comment by schneidmaster** [comment]
Hi there -- thanks for submitting the PR! Two comments:

1) Would you mind undoing all the whitespace changes? It looks like all the lines were changed from 2 spaces to 4. This makes it difficult to read what changed.

2) I think the `beautify` option should be false by default, since that is the current behavior.

**Comment by shaildyp** [comment]
My IDE formatted the whitespacers, sorry about that. I can fix it tomorrow.

I reckon the default setting should be true for XML readability. But I can understand that the update needs to inline with release version.

**Comment by schneidmaster** [comment]
No worries, I'll review again when the whitespace is cleaned up.

After thinking about it further I agree with you that the sitemap should be beautified by default. I'll just bump the middle version number to account for the nontrivial change.

**Comment by schneidmaster** [comment]
Hey @shaildyp -- I did a good bit of work on master, expanding customization + streamlining config. I'm going to go ahead and close the PR since it's now pretty conflicted. But feel free to branch off of the latest code and resubmit your PR for review (with whitespace as we discussed above).

**Pull request closed without merging**
